CREATE TABLE IF NOT EXISTS device_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform TEXT NOT NULL CHECK (platform IN ('android', 'ios')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, token)
);

ALTER TABLE device_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert their own device tokens"
ON device_tokens FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete their own device tokens"
ON device_tokens FOR DELETE
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Users can read their own device tokens"
ON device_tokens FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE OR REPLACE FUNCTION get_house_device_tokens(house_id UUID)
RETURNS TABLE(token TEXT, platform TEXT) AS $$
BEGIN
  RETURN QUERY
  SELECT dt.token, dt.platform
  FROM device_tokens dt
  JOIN profiles p ON p.id = dt.user_id
  WHERE p.house_id = get_house_device_tokens.house_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION upsert_device_token(
  p_token TEXT,
  p_platform TEXT
) RETURNS VOID AS $$
BEGIN
  INSERT INTO device_tokens (user_id, token, platform)
  VALUES (auth.uid(), p_token, p_platform)
  ON CONFLICT (user_id, token)
  DO UPDATE SET platform = p_platform, updated_at = NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
